(defclass trie ()
  ((children :initform nil :accessor trie-children)
   (value :initarg :value  :accessor trie-value)))

(defmethod trie-insert (trie key value) 
  (if (zerop (length key))
      (setf (trie-value trie) value)
      (let ((sub-trie (cif pair (assoc (elt key 0) (trie-children trie))
			   (cdr pair)
			   (let ((new-trie (make-instance 'trie)))
			     (push (cons (elt key 0) new-trie) (trie-children trie))
			     new-trie))))
	(trie-insert sub-trie (subseq key 1) value))))
